workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS'
      when: never
    - if: '$CI_COMMIT_BRANCH'
    - if: '$CI_COMMIT_TAG'

stages:
  - validate
  - test
  - build
  - security
  - integration
  - deploy_staging
  - deploy_production
  - rollback

default:
  interruptible: true
  retry:
    max: 1
    when:
      - runner_system_failure
      - stuck_or_timeout_failure

include:
  - local: .gitlab/ci/common.yml
  - local: .gitlab/ci/validate.yml
  - local: .gitlab/ci/terraform.yml
  - local: .gitlab/ci/backend.yml
  - local: .gitlab/ci/frontend.yml
  - local: .gitlab/ci/security.yml
  - local: .gitlab/ci/build.yml
  - local: .gitlab/ci/integration.yml
  - local: .gitlab/ci/deploy.yml
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Dependency-Scanning.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
